package com.relations;
// Generated Nov 24, 2015 10:01:10 AM by Hibernate Tools 4.3.1



/**
 * OrderDetail generated by hbm2java
 */
public class OrderDetail  implements java.io.Serializable {


     private Integer id;
     private String item;
     private Integer lineNumber;
     private Orders orderRec;

    public OrderDetail() {
    }

	
    public OrderDetail(Orders orderRec) {
        this.orderRec = orderRec;
    }
    public OrderDetail(String item, Integer lineNumber, Orders orderRec) {
       this.item = item;
       this.lineNumber = lineNumber;
       this.orderRec = orderRec;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getItem() {
        return this.item;
    }
    
    public void setItem(String item) {
        this.item = item;
    }
    public Integer getLineNumber() {
        return this.lineNumber;
    }
    
    public void setLineNumber(Integer lineNumber) {
        this.lineNumber = lineNumber;
    }
    public Orders getOrderRec() {
        return this.orderRec;
    }
    
    public void setOrderRec(Orders orderRec) {
        this.orderRec = orderRec;
    }




}


