package com.relations;
// Generated Nov 24, 2015 10:01:10 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * PurchaseOrderDetail generated by hbm2java
 */
public class PurchaseOrderDetail implements java.io.Serializable {

    private int podetailId;
    private PurchaseOrderHeader purchaseOrderHeader;
    private int lineNumber;
    private String item;
    private BigDecimal quantity;

    public PurchaseOrderDetail() {
    }

    public PurchaseOrderDetail(PurchaseOrderHeader purchaseOrderHeader, int poheaderId, int lineNumber, String item, BigDecimal quantity) {
        this.purchaseOrderHeader = purchaseOrderHeader;
        
        this.lineNumber = lineNumber;
        this.item = item;
        this.quantity = quantity;
    }

    public int getPodetailId() {
        return this.podetailId;
    }

    public void setPodetailId(int podetailId) {
        this.podetailId = podetailId;
    }

    public PurchaseOrderHeader getPurchaseOrderHeader() {
        return this.purchaseOrderHeader;
    }

    public void setPurchaseOrderHeader(PurchaseOrderHeader purchaseOrderHeader) {
        this.purchaseOrderHeader = purchaseOrderHeader;
    }

    public int getLineNumber() {
        return this.lineNumber;
    }

    public void setLineNumber(int lineNumber) {
        this.lineNumber = lineNumber;
    }

    public String getItem() {
        return this.item;
    }

    public void setItem(String item) {
        this.item = item;
    }

    public BigDecimal getQuantity() {
        return this.quantity;
    }

    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

}
